CREATE TABLE "RPA"."A_PC_SCGDWH_TAB" 
   (	"SCGDH" VARCHAR2(100) NOT NULL ENABLE, 
	"JHRQ" VARCHAR2(20), 
	"JHSJ" VARCHAR2(20), 
	"YWY" VARCHAR2(20), 
	"YLKW" VARCHAR2(20), 
	"GSXS" NUMBER(20,1), 
	"JHKSRQ" VARCHAR2(20), 
	"JHKSSJ" VARCHAR2(20), 
	"BC" VARCHAR2(20), 
	"ZZSCRQ" VARCHAR2(20), 
	"ZZSCSJ" VARCHAR2(20), 
	"GDJHZT" NUMBER(20,0), 
	 CONSTRAINT "CK_JHRQ_FORMAT" CHECK (REGEXP_LIKE(JHRQ, '^[0-9]{4}-[0-9]{2}-[0-9]{2}$') OR JHRQ IS NULL) ENABLE, 
	 CONSTRAINT "CK_JHSJ_FORMAT" CHECK (REGEXP_LIKE(JHSJ, '^[0-9]{2}:[0-9]{2}:[0-9]{2}$') OR JHSJ IS NULL) ENABLE, 
	 CONSTRAINT "PK_A_PC_SCGDWH_TAB" PRIMARY KEY ("SCGDH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "CK_SCGHD_LENGTH" CHECK (LENGTH(SCGDH) > 0) ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  CREATE UNIQUE INDEX "RPA"."PK_A_PC_SCGDWH_TAB" ON "RPA"."A_PC_SCGDWH_TAB" ("SCGDH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  ALTER TABLE "RPA"."A_PC_SCGDWH_TAB" MODIFY ("SCGDH" NOT NULL ENABLE);
  ALTER TABLE "RPA"."A_PC_SCGDWH_TAB" ADD CONSTRAINT "CK_SCGHD_LENGTH" CHECK (LENGTH(SCGDH) > 0) ENABLE;
  ALTER TABLE "RPA"."A_PC_SCGDWH_TAB" ADD CONSTRAINT "CK_JHRQ_FORMAT" CHECK (REGEXP_LIKE(JHRQ, '^[0-9]{4}-[0-9]{2}-[0-9]{2}$') OR JHRQ IS NULL) ENABLE;
  ALTER TABLE "RPA"."A_PC_SCGDWH_TAB" ADD CONSTRAINT "CK_JHSJ_FORMAT" CHECK (REGEXP_LIKE(JHSJ, '^[0-9]{2}:[0-9]{2}:[0-9]{2}$') OR JHSJ IS NULL) ENABLE;
  ALTER TABLE "RPA"."A_PC_SCGDWH_TAB" ADD CONSTRAINT "PK_A_PC_SCGDWH_TAB" PRIMARY KEY ("SCGDH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
   COMMENT ON COLUMN "RPA"."A_PC_SCGDWH_TAB"."SCGDH" IS '生产工单号';
   COMMENT ON COLUMN "RPA"."A_PC_SCGDWH_TAB"."JHRQ" IS '交货日期，格式：YYYY-MM-DD';
   COMMENT ON COLUMN "RPA"."A_PC_SCGDWH_TAB"."JHSJ" IS '交货时间，格式：HH24:MI:SS';
   COMMENT ON COLUMN "RPA"."A_PC_SCGDWH_TAB"."YWY" IS '业务员';
   COMMENT ON COLUMN "RPA"."A_PC_SCGDWH_TAB"."YLKW" IS '原料库位';
   COMMENT ON COLUMN "RPA"."A_PC_SCGDWH_TAB"."GSXS" IS '工时（小时）';
   COMMENT ON COLUMN "RPA"."A_PC_SCGDWH_TAB"."JHKSRQ" IS '计划开始日期';
   COMMENT ON COLUMN "RPA"."A_PC_SCGDWH_TAB"."JHKSSJ" IS '计划开始时间';
   COMMENT ON COLUMN "RPA"."A_PC_SCGDWH_TAB"."BC" IS '班次';
   COMMENT ON COLUMN "RPA"."A_PC_SCGDWH_TAB"."ZZSCRQ" IS '最早开始日期';
   COMMENT ON COLUMN "RPA"."A_PC_SCGDWH_TAB"."ZZSCSJ" IS '最早开始时间';
   COMMENT ON COLUMN "RPA"."A_PC_SCGDWH_TAB"."GDJHZT" IS '工单计划状态';
   COMMENT ON TABLE "RPA"."A_PC_SCGDWH_TAB"  IS '生产工单维护表';